export default function ({
    palette,
    semanticMapping: {
        annotation,
        attribute,
        comment,
        constant,
        func,
        keyword,
        string,
        text,
        type,
        variable,
    },
}) {
    return {
        attribute: { color: attribute },
        boolean: { color: constant },
        comment: { color: comment },
        'comment.doc': { color: comment },
        constant: { color: constant },
        constructor: { color: func },
        embedded: { color: variable },
        emphasis: { font_style: 'italic' },
        'emphasis.strong': { font_weight: 700 },
        enum: { color: type },
        function: { color: func },
        hint: { color: palette.cyan.fg2 },
        keyword: { color: keyword },
        label: { color: variable },
        link_text: { color: palette.blue.fg1 },
        link_uri: { color: palette.blue.fg1 },
        number: { color: constant },
        operator: { color: text },
        predictive: { color: palette.fg3 },
        preproc: { color: annotation },
        primary: { color: variable },
        property: { color: variable },
        punctuation: { color: text },
        'punctuation.bracket': { color: text },
        'punctuation.delimiter': { color: text },
        'punctuation.list_marker': { color: palette.magenta.fg2 },
        'punctuation.special': { color: text },
        string: { color: string },
        'string.escape': { color: constant },
        'string.regex': { color: constant },
        'string.special': { color: constant },
        'string.special.symbol': { color: variable },
        tag: { color: type },
        'text.literal': { color: text },
        title: { color: palette.magenta.fg1 },
        type: { color: type },
        variable: { color: variable },
        'variable.special': { color: text },
        variant: { color: variable },
    };
}
