const transparent = '#00000000';

export default function (palette) {
    return {
        'background.appearance': 'opaque',
        background: palette.bg2,
        'surface.background': palette.bg2,
        'elevated_surface.background': palette.bg2,

        border: palette.bg3,
        'border.variant': palette.bg2,
        'border.focused': palette.bg3,
        'border.selected': palette.bg3,
        'border.disabled': palette.bg2,
        'border.transparent': transparent,

        'element.background': palette.bg2,
        'element.hover': palette.bg3,
        'element.active': palette.bg3,
        'element.selected': palette.bg3,
        'element.disabled': palette.bg2,
        'ghost_element.background': transparent,
        'ghost_element.hover': palette.bg2,
        'ghost_element.active': palette.bg3,
        'ghost_element.selected': palette.bg3,
        'ghost_element.disabled': palette.bg2,
        'drop_target.background': `${palette.bg3}80`,

        text: palette.fg1,
        'text.muted': palette.fg2,
        'text.placeholder': palette.fg3,
        'text.disabled': palette.fg3,
        'text.accent': palette.cyan.fg1,
        icon: palette.fg1,
        'icon.muted': palette.fg2,
        'icon.disabled': palette.fg3,
        'icon.placeholder': palette.fg3,
        'icon.accent': palette.cyan.fg1,

        'title_bar.background': palette.bg2,
        'title_bar.inactive_background': palette.bg2,
        'status_bar.background': palette.bg2,
        'toolbar.background': palette.bg1,
        'tab_bar.background': palette.bg2,
        'tab.active_background': palette.bg1,
        'tab.inactive_background': palette.bg2,

        'panel.background': palette.bg1,
        'panel.focused_border': palette.bg3,
        'panel.indent_guide': palette.bg3,
        'panel.indent_guide_active': palette.magenta.fg3,
        'panel.indent_guide_hover': palette.fg3,
        'pane.focused_border': palette.bg3,
        'pane_group.border': palette.bg3,

        'editor.background': palette.bg1,
        'editor.foreground': palette.fg1,
        'editor.gutter.background': palette.bg2,
        'editor.subheader.background': palette.bg2,
        'editor.active_line.background': palette.bg2,
        'editor.highlighted_line.background': palette.bg2,
        'editor.line_number': palette.fg3,
        'editor.active_line_number': palette.fg1,
        'editor.invisible': palette.bg3,
        'editor.indent_guide': palette.bg3,
        'editor.indent_guide_active': palette.magenta.fg3,
        'editor.wrap_guide': palette.bg3,
        'editor.active_wrap_guide': palette.fg3,
        'editor.document_highlight.read_background': palette.bg3,
        'editor.document_highlight.write_background': palette.bg3,
        'editor.document_highlight.bracket_background': palette.bg3,

        'search.match_background': palette.yellow.bg1,
        'scrollbar.thumb.background': `${palette.fg3}40`,
        'scrollbar.thumb.hover_background': `${palette.fg3}80`,
        'scrollbar.thumb.border': transparent,
        'scrollbar.track.background': transparent,
        'scrollbar.track.border': transparent,
        'link_text.hover': palette.blue.fg1,

        // Diagnostics
        error: palette.red.fg2,
        'error.background': palette.red.bg1,
        'error.border': palette.red.fg2,
        warning: palette.yellow.fg2,
        'warning.background': palette.yellow.bg1,
        'warning.border': palette.yellow.fg2,
        info: palette.cyan.fg2,
        'info.background': palette.cyan.bg1,
        'info.border': palette.cyan.fg2,
        hint: palette.fg3,
        'hint.background': palette.bg2,
        'hint.border': palette.bg3,
        success: palette.green.fg2,
        'success.background': palette.green.bg1,
        'success.border': palette.green.bg2,

        // Version control
        conflict: palette.red.fg1,
        'conflict.background': palette.red.bg1,
        'conflict.border': palette.red.bg2,
        created: palette.green.fg1,
        'created.background': palette.green.bg1,
        'created.border': palette.green.bg2,
        deleted: palette.red.fg1,
        'deleted.background': palette.red.bg1,
        'deleted.border': palette.red.bg2,
        modified: palette.yellow.fg1,
        'modified.background': palette.yellow.bg1,
        'modified.border': palette.yellow.bg2,
        renamed: palette.blue.fg1,
        'renamed.background': palette.blue.bg1,
        'renamed.border': palette.blue.bg1,

        // Muted statuses
        hidden: palette.fg3,
        'hidden.background': palette.bg2,
        'hidden.border': palette.bg3,
        ignored: palette.fg2,
        'ignored.background': palette.bg2,
        'ignored.border': palette.bg3,
        predictive: palette.fg3,
        'predictive.background': palette.bg2,
        'predictive.border': palette.bg3,
        unreachable: palette.fg3,
        'unreachable.background': palette.bg2,
        'unreachable.border': palette.bg3,

        'terminal.background': palette.bg1,
        'terminal.foreground': palette.fg1,
        'terminal.bright_foreground': palette.fg1,
        'terminal.dim_foreground': palette.fg2,
        'terminal.ansi.background': palette.bg1,
        'terminal.ansi.black': palette.bg1,
        'terminal.ansi.bright_black': palette.fg3,
        'terminal.ansi.dim_black': palette.bg1,
        'terminal.ansi.red': palette.red.fg1,
        'terminal.ansi.bright_red': palette.red.fg2,
        'terminal.ansi.dim_red': palette.red.fg1,
        'terminal.ansi.green': palette.green.fg1,
        'terminal.ansi.bright_green': palette.green.fg2,
        'terminal.ansi.dim_green': palette.green.fg1,
        'terminal.ansi.yellow': palette.yellow.fg1,
        'terminal.ansi.bright_yellow': palette.yellow.fg2,
        'terminal.ansi.dim_yellow': palette.yellow.fg1,
        'terminal.ansi.blue': palette.blue.fg1,
        'terminal.ansi.bright_blue': palette.blue.fg2,
        'terminal.ansi.dim_blue': palette.blue.fg1,
        'terminal.ansi.magenta': palette.magenta.fg1,
        'terminal.ansi.bright_magenta': palette.magenta.fg2,
        'terminal.ansi.dim_magenta': palette.magenta.fg1,
        'terminal.ansi.cyan': palette.cyan.fg1,
        'terminal.ansi.bright_cyan': palette.cyan.fg2,
        'terminal.ansi.dim_cyan': palette.cyan.fg1,
        'terminal.ansi.white': palette.fg1,
        'terminal.ansi.bright_white': palette.bg1,
        'terminal.ansi.dim_white': palette.fg1,

        accents: [
            palette.cyan.fg1,
            palette.magenta.fg1,
            palette.blue.fg1,
            palette.green.fg1,
            palette.yellow.fg1,
            palette.purple.fg1,
            palette.red.fg1,
        ],
        players: [
            {
                cursor: palette.fg1,
                background: palette.fg1,
                selection: palette.cyan.bg1,
            },
            {
                cursor: palette.magenta.fg1,
                background: palette.magenta.fg1,
                selection: `${palette.magenta.fg1}33`,
            },
            {
                cursor: palette.blue.fg1,
                background: palette.blue.fg1,
                selection: `${palette.blue.fg1}33`,
            },
            {
                cursor: palette.green.fg1,
                background: palette.green.fg1,
                selection: `${palette.green.fg1}33`,
            },
            {
                cursor: palette.yellow.fg1,
                background: palette.yellow.fg1,
                selection: `${palette.yellow.fg1}33`,
            },
            {
                cursor: palette.purple.fg1,
                background: palette.purple.fg1,
                selection: `${palette.purple.fg1}33`,
            },
            {
                cursor: palette.cyan.fg1,
                background: palette.cyan.fg1,
                selection: `${palette.cyan.fg1}33`,
            },
            {
                cursor: palette.red.fg1,
                background: palette.red.fg1,
                selection: `${palette.red.fg1}33`,
            },
        ],
    };
}
